// Package data holds site content types and the loader that parses seed-cache.json.
// Re-run the scraper in the source repo and replace seed-cache.json to refresh.
package data

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"log"
	"math"
	"strings"
	"time"
)

//go:embed seed-cache.json
var seedJSON []byte

type SiteData struct {
	GitHub   []Project    `json:"github_projects"`
	LinkedIn LinkedInData `json:"linkedin_data"`
	Strava   StravaData   `json:"strava_data"`
}

type LinkedInData struct {
	Profile    Profile  `json:"profile"`
	Name       string   `json:"name"`
	Headline   string   `json:"headline"`
	Location   string   `json:"location"`
	About      string   `json:"about"`
	Experience []Job    `json:"experience"`
	Education  []School `json:"education"`
	Skills     []string `json:"skills"`
}

type Profile struct {
	Name     string `json:"name"`
	PhotoURL string `json:"photo_url"`
}

type Job struct {
	Title    string `json:"title"`
	Company  string `json:"company"`
	Type     string `json:"type"`
	Period   string `json:"period"`
	Duration string `json:"duration"`
	Desc     string `json:"description"`
}

type School struct {
	School string `json:"school"`
	Degree string `json:"degree"`
	Period string `json:"period"`
}

type Project struct {
	Name     string        `json:"name"`
	Desc     string        `json:"description"`
	URL      string        `json:"url"`
	Stars    int           `json:"stars"`
	Language string        `json:"language"`
	Topics   []string      `json:"topics"`
	Images   []string      `json:"images"`
	Featured bool          `json:"featured"`
	Links    []ProjectLink `json:"links"`
}

type ProjectLink struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

// StravaData is generated by the data pipeline and embedded into the homepage.
// Distances are stored in meters and durations in seconds to keep the data
// source precise; display helpers convert them at render time.
type StravaData struct {
	GeneratedAt       string              `json:"generated_at,omitempty"`
	TotalStats        StravaStats         `json:"total_stats"`
	YearToDateStats   StravaStats         `json:"year_to_date_stats"`
	RecentActivities  []StravaActivity    `json:"recent_activities"`
	BestActivities    StravaBestRecords   `json:"best_activities"`
	PersonalRecords   []StravaRecord      `json:"personal_records"`
	Disciplines       []StravaDiscipline  `json:"disciplines"`
	MonthlyActivities []StravaMonthBucket `json:"monthly_activities,omitempty"`
	Year              string              `json:"year,omitempty"`
}

type StravaStats struct {
	Count         int     `json:"count"`
	Distance      float64 `json:"distance"`
	MovingTime    int     `json:"moving_time"`
	ElapsedTime   int     `json:"elapsed_time"`
	ElevationGain float64 `json:"elevation_gain"`
}

type StravaActivity struct {
	ID                 int64   `json:"id,omitempty"`
	Name               string  `json:"name"`
	Distance           float64 `json:"distance"`
	MovingTime         int     `json:"moving_time"`
	ElapsedTime        int     `json:"elapsed_time,omitempty"`
	TotalElevationGain float64 `json:"total_elevation_gain,omitempty"`
	Type               string  `json:"type"`
	StartDate          string  `json:"start_date,omitempty"`
	StartDateLocal     string  `json:"start_date_local,omitempty"`
	AveragePace        float64 `json:"average_pace,omitempty"`
	AverageSpeed       float64 `json:"average_speed,omitempty"`
	MaxSpeed           float64 `json:"max_speed,omitempty"`
	AverageHeartrate   float64 `json:"average_heartrate,omitempty"`
	MaxHeartrate       float64 `json:"max_heartrate,omitempty"`
	Calories           float64 `json:"calories,omitempty"`
}

type StravaBestRecords struct {
	LongestDistance StravaActivity `json:"longest_distance"`
	LongestTime     StravaActivity `json:"longest_time"`
	FastestPace     StravaActivity `json:"fastest_pace"`
	MostElevation   StravaActivity `json:"most_elevation"`
}

type StravaRecord struct {
	Type     string         `json:"type"`
	Time     int            `json:"time"`
	Distance float64        `json:"distance"`
	Date     string         `json:"date"`
	Activity StravaActivity `json:"activity"`
}

type StravaDiscipline struct {
	Type          string           `json:"type"`
	Label         string           `json:"label"`
	Count         int              `json:"count"`
	TotalTime     int              `json:"total_time"`
	TotalDistance float64          `json:"total_distance"`
	AvgHeartrate  float64          `json:"avg_heartrate"`
	Activities    []StravaActivity `json:"activities"`
}

type StravaMonthBucket struct {
	Month    string  `json:"month"`
	Count    int     `json:"count"`
	Distance float64 `json:"distance"`
	Time     int     `json:"time"`
}

// SkillGroup is a hand-curated grouping of the flat LinkedIn skills list plus
// extra skills not exported by LinkedIn.
type SkillGroup struct {
	Label  string
	Tone   string
	Skills []string
}

var skillGroups = []SkillGroup{
	{"Languages", "violet", []string{"Go", "Rust", "TypeScript", "JavaScript", "Python", "Kotlin", "Java", "C#"}},
	{"Web", "sky", []string{"HTML", "CSS", "Svelte", "SvelteKit", "AngularJS", "Angular", "ASP.NET", ".NET"}},
	{"Infra / Homelab", "lime", []string{"Docker", "Ansible", "Linux", "Unraid", "Tailscale", "Caddy", "CI/CD"}},
	{"Security", "yellow", []string{"Cybersecurity", "Network Security", "IAM", "Prolog", "PAM"}},
	{"Embedded / BLE", "pink", []string{"ESP32", "BLE", "Dexcom G7", "Nightscout", "Kotlin Multiplatform"}},
	{"Ops / Data", "mint", []string{"SQLite", "VictoriaMetrics", "Grafana", "slog", "WebGL"}},
}

// Load parses and returns the embedded site data. Panics on bad JSON (should not happen in prod).
func Load() SiteData {
	var d SiteData
	if err := json.Unmarshal(seedJSON, &d); err != nil {
		log.Fatalf("data: parse seed-cache.json: %v", err)
	}
	d.Strava.Normalize()
	return d
}

// FeaturedProjects returns projects marked featured, excluding meta-entries.
func (d SiteData) FeaturedProjects() []Project {
	var out []Project
	for _, p := range d.GitHub {
		if p.Featured && !strings.EqualFold(p.Name, "homepage") {
			out = append(out, p)
		}
	}
	return out
}

// AllProjects returns all non-featured, non-meta projects.
func (d SiteData) AllProjects() []Project {
	var out []Project
	for _, p := range d.GitHub {
		if !p.Featured && !strings.EqualFold(p.Name, "homepage") {
			out = append(out, p)
		}
	}
	return out
}

// HasStrava returns true when the generated data contains enough public
// activity aggregate data to render a useful section.
func (d SiteData) HasStrava() bool {
	return d.Strava.TotalStats.Count > 0 || len(d.Strava.RecentActivities) > 0
}

// SkillGroups returns the curated skill groups.
func SkillGroups() []SkillGroup { return skillGroups }

// DisplayName returns the short first name.
func (d LinkedInData) DisplayName() string {
	parts := strings.Fields(d.Name)
	if len(parts) > 0 {
		return parts[0]
	}
	return d.Name
}

// RelevantExperience returns the top N non-trivial experience items.
func (d LinkedInData) RelevantExperience(n int) []Job {
	// Filter out very old/minor entries (Zivildienst, early student internships)
	skip := map[string]bool{
		"HerzReha Bad Ischl": true,
		"ENGEL":              true,
	}
	var out []Job
	for _, j := range d.Experience {
		if skip[j.Company] {
			continue
		}
		out = append(out, j)
		if len(out) >= n {
			break
		}
	}
	return out
}

// LocalImages returns only local (non-URL) images for a project.
func (p Project) LocalImages() []string {
	var out []string
	for _, img := range p.Images {
		if strings.HasPrefix(img, "/") {
			out = append(out, img)
		}
	}
	return out
}

func (s *StravaData) Normalize() {
	for i := range s.RecentActivities {
		s.RecentActivities[i].Normalize()
	}
	for i := range s.Disciplines {
		for j := range s.Disciplines[i].Activities {
			s.Disciplines[i].Activities[j].Normalize()
		}
	}
	s.BestActivities.LongestDistance.Normalize()
	s.BestActivities.LongestTime.Normalize()
	s.BestActivities.FastestPace.Normalize()
	s.BestActivities.MostElevation.Normalize()
	for i := range s.PersonalRecords {
		s.PersonalRecords[i].Activity.Normalize()
		if s.PersonalRecords[i].Date == "" {
			s.PersonalRecords[i].Date = s.PersonalRecords[i].Activity.DisplayDate()
		}
	}
	if s.Year == "" {
		s.Year = time.Now().Format("2006")
	}
}

func (a *StravaActivity) Normalize() {
	if a.StartDate == "" {
		a.StartDate = a.StartDateLocal
	}
	if a.ElapsedTime == 0 {
		a.ElapsedTime = a.MovingTime
	}
	if a.AveragePace == 0 && a.AverageSpeed > 0 {
		a.AveragePace = 1000 / (a.AverageSpeed * 60)
	}
}

func (a StravaActivity) DisplayDate() string {
	raw := a.StartDate
	if raw == "" {
		raw = a.StartDateLocal
	}
	if raw == "" {
		return ""
	}
	for _, layout := range []string{time.RFC3339, "2006-01-02T15:04:05Z07:00", "2006-01-02"} {
		t, err := time.Parse(layout, raw)
		if err == nil {
			return t.Format("Jan 2006")
		}
	}
	if len(raw) >= 7 {
		return raw[:7]
	}
	return raw
}

func DistanceKM(meters float64) float64 {
	return math.Round(meters/100) / 10
}

func DurationHours(seconds int) float64 {
	return math.Round(float64(seconds)/36) / 100
}

func PaceLabel(minutesPerKM float64) string {
	if minutesPerKM <= 0 {
		return "n/a"
	}
	minutes := int(minutesPerKM)
	seconds := int(math.Round((minutesPerKM - float64(minutes)) * 60))
	if seconds == 60 {
		minutes++
		seconds = 0
	}
	return fmt.Sprintf("%d:%02d /km", minutes, seconds)
}

// LogoForCompany maps LinkedIn company names to local logo paths.
func LogoForCompany(company string) string {
	m := map[string]string{
		"Dynatrace":                        "/static/logos/dynatrace.jpg",
		"Johannes Kepler Universität Linz": "/static/logos/jku.jpg",
		"ventopay gmbh":                    "/static/logos/ventopay.jpg",
		"Bosch":                            "/static/logos/bosch.jpg",
		"Bosch Rexroth":                    "/static/logos/bosch-rexroth.jpg",
		"ENGEL":                            "/static/logos/engel.jpg",
		"HerzReha Bad Ischl":               "/static/logos/herzreha-bad-ischl.jpg",
	}
	return m[company]
}

// LogoForSchool maps school names to local logo paths.
func LogoForSchool(school string) string {
	m := map[string]string{
		"Johannes Kepler Universität Linz": "/static/logos/jku.jpg",
	}
	return m[school]
}

// TechIcon maps a lowercase tech/topic keyword to an Iconify icon name.
// Returns "" if no icon is known for the keyword.
func TechIcon(keyword string) string {
	m := map[string]string{
		// ── languages ────────────────────────────────────────────────
		"go":         "simple-icons:go",
		"golang":     "simple-icons:go",
		"rust":       "simple-icons:rust",
		"typescript": "simple-icons:typescript",
		"javascript": "simple-icons:javascript",
		"python":     "simple-icons:python",
		"kotlin":     "simple-icons:kotlin",
		"java":       "lucide:code-2",
		"c#":         "simple-icons:csharp",
		"csharp":     "simple-icons:csharp",
		"nodejs":     "simple-icons:nodedotjs",
		"node.js":    "simple-icons:nodedotjs",
		// ── web frameworks ────────────────────────────────────────────
		"svelte":         "simple-icons:svelte",
		"sveltekit":      "simple-icons:svelte",
		"tailwindcss":    "simple-icons:tailwindcss",
		"html":           "simple-icons:html5",
		"css":            "simple-icons:css3",
		"angular":        "simple-icons:angular",
		"angularjs":      "simple-icons:angularjs",
		"asp.net":        "simple-icons:dotnet",
		".net":           "simple-icons:dotnet",
		".net-framework": "simple-icons:dotnet",
		"dotnet":         "simple-icons:dotnet",
		// ── infra / homelab ──────────────────────────────────────────
		"docker":     "simple-icons:docker",
		"linux":      "simple-icons:linux",
		"ansible":    "simple-icons:ansible",
		"tailscale":  "simple-icons:tailscale",
		"devops":     "lucide:workflow",
		"cicd":       "lucide:git-branch",
		"ci/cd":      "lucide:git-branch",
		"automation": "lucide:bot",
		"homelab":    "lucide:server",
		"unraid":     "lucide:hard-drive",
		"caddy":      "lucide:shield",
		"template":   "lucide:layers",
		// ── web general ──────────────────────────────────────────────
		"web":           "lucide:globe",
		"webgl":         "lucide:box",
		"3d":            "lucide:box",
		"animation":     "lucide:zap",
		"multiplatform": "lucide:layers",
		"plugin":        "lucide:puzzle",
		// ── data / ops ───────────────────────────────────────────────
		"database":          "lucide:database",
		"sqlite":            "lucide:database",
		"monitoring":        "lucide:activity",
		"victoriametrics":   "simple-icons:victoriametrics",
		"grafana":           "simple-icons:grafana",
		"slog":              "lucide:scroll",
		"networking":        "lucide:network",
		"power-consumption": "lucide:zap",
		// ── security ─────────────────────────────────────────────────
		"security":           "lucide:shield",
		"cybersecurity":      "lucide:shield",
		"network security":   "lucide:network",
		"netzwerksicherheit": "lucide:network",
		"pam":                "lucide:key",
		"iam":                "lucide:user-check",
		"prolog":             "lucide:brain",
		// ── embedded / BLE ───────────────────────────────────────────
		"esp32":                "lucide:cpu",
		"ble":                  "lucide:bluetooth",
		"dexcom g7":            "lucide:activity",
		"nightscout":           "lucide:activity",
		"kotlin multiplatform": "simple-icons:kotlin",
		"diabetes":             "lucide:activity",
		"healthcare":           "lucide:activity",
		// ── research / ai ────────────────────────────────────────────
		"ai":               "lucide:brain",
		"machine-learning": "lucide:brain",
		"lstm":             "lucide:brain",
		"deep-learning":    "lucide:brain",
		"research":         "lucide:microscope",
		"thesis":           "lucide:microscope",
		// ── media ────────────────────────────────────────────────────
		"music": "lucide:music",
		"audio": "lucide:music",
		// ── project tools ────────────────────────────────────────────
		"flexbar":    "lucide:cpu",
		"streamdeck": "lucide:cpu",
		"desktop":    "lucide:cpu",
		"mobile":     "lucide:cpu",
		"wails":      "simple-icons:go",
		"github":     "simple-icons:github",
		// ── linkedin exported names (German) ─────────────────────────
		"it-infrastruktur":            "lucide:server",
		"it-management":               "lucide:user-check",
		"softwareentwicklung":         "lucide:code-2",
		"kontinuierliche integration": "lucide:git-branch",
		"netzwerkadministration":      "lucide:network",
	}
	return m[strings.ToLower(keyword)]
}
