package pages

import (
	g "maragu.dev/gomponents"
	h "maragu.dev/gomponents/html"

	"mljr-web/internal/i18n"
	hpdata "mljr-web/projects/homepage/data"
	"mljr-web/ui"
	uiform "mljr-web/ui/form"
	"mljr-web/ui/icon"
	"mljr-web/ui/layout"
	"mljr-web/ui/primitive"
	"mljr-web/ui/special"
	"mljr-web/ui/token"
)

func contactSection(num string, content hpdata.ContactContent, lang string) g.Node {
	// Submit expression: read the hidden input generated by altcha-widget into
	// a Datastar signal, then POST the contact form signals.
	submitExpr := `$altcha = document.querySelector('altcha-widget[name=altcha] input[name=altcha]')?.value || ''; $sending = true; @post('/api/contact')`

	return h.Section(
		h.ID("contact"),
		h.Style("padding:var(--sp-12) 0"),
		// seed signals for form state
		h.Div(
			ui.Signals(`{name:'',email:'',message:'',altcha:'',sending:false,nameError:'',emailError:'',msgError:''}`),
		),
		layout.Container(layout.ContainerProps{},
			layout.Grid(layout.GridProps{},
				layout.Col(layout.ColProps{Span: 5},
					h.Div(h.Style("display:flex;flex-direction:column;gap:var(--sp-5);height:100%"),
						sectionHeader(num, i18n.T(lang, "sections.contact.title"), i18n.T(lang, "sections.contact.sub"), token.TonePink),
						h.P(h.Style("color:var(--muted);font-size:var(--t-base);line-height:1.6;margin:0"),
							g.Text(content.Intro),
						),
						primitive.Card(primitive.CardProps{Tone: token.ToneYellow},
							primitive.Heading(primitive.HeadingProps{Level: 4}, g.Text(i18n.T(lang, "contact.currently"))),
							h.Ul(h.Style("margin:var(--sp-2) 0 0;padding-left:var(--sp-5);display:flex;flex-direction:column;gap:var(--sp-3);font-size:var(--t-sm)"),
								g.Group(func() []g.Node {
									nodes := make([]g.Node, 0, len(content.Currently))
									for _, c := range content.Currently {
										nodes = append(nodes, h.Li(g.Text(c)))
									}
									return nodes
								}()),
							),
						),
						h.Div(
							h.Style("display:flex;flex-direction:column;gap:var(--sp-2);margin-top:auto"),
							h.A(h.Href("mailto:reinemic2.0@gmail.com"),
								primitive.Button(primitive.ButtonProps{Variant: token.Outline, Attrs: []g.Node{h.Style("width:100%")}},
									icon.Icon("lucide:mail"),
									g.Text("reinemic2.0@gmail.com"),
								),
							),
							h.A(h.Href("https://github.com/MrCodeEU"), g.Attr("target", "_blank"),
								primitive.Button(primitive.ButtonProps{Variant: token.Outline, Attrs: []g.Node{h.Style("width:100%")}},
									icon.Icon("simple-icons:github"),
									g.Text("github.com/MrCodeEU"),
								),
							),
						),
					),
				),
				layout.Col(layout.ColProps{Span: 7},
					h.Form(
						h.ID("contact-form"),
						h.Style("position:relative"),
						ui.On("submit__prevent", submitExpr),
						special.HoneypotField("_hp"),
						layout.Stack(layout.StackProps{},
							uiform.Field(uiform.FieldProps{
								Label:    i18n.T(lang, "contact.name_label"),
								ErrorFor: "name",
							}, uiform.Input(uiform.InputProps{
								Type:        "text",
								Placeholder: i18n.T(lang, "contact.name_placeholder"),
								Signal:      "name",
								Required:    true,
							})),
							uiform.Field(uiform.FieldProps{
								Label:    i18n.T(lang, "contact.email_label"),
								ErrorFor: "email",
							}, uiform.Input(uiform.InputProps{
								Type:        "email",
								Placeholder: i18n.T(lang, "contact.email_placeholder"),
								Signal:      "email",
								Required:    true,
							})),
							uiform.Field(uiform.FieldProps{
								Label:    i18n.T(lang, "contact.message_label"),
								ErrorFor: "msg",
							}, uiform.Textarea(uiform.TextareaProps{
								Placeholder: i18n.T(lang, "contact.message_placeholder"),
								Signal:      "message",
								Rows:        5,
								Required:    true,
							})),
							// altcha captcha widget
							special.Captcha(special.CaptchaProps{ChallengeURL: "/api/altcha"}),
							// error display from server
							h.Div(h.ID("contact-error")),
							// submit
							primitive.Button(primitive.ButtonProps{
								Variant: token.Primary,
								Size:    token.SizeLG,
								Type:    "submit",
								Attrs: []g.Node{
									ui.Indicator("sending"),
									g.Attr("data-attr", `{"disabled": $sending}`),
								},
							},
								h.Span(ui.Show("!$sending"), g.Text(i18n.T(lang, "contact.send")), icon.Icon("lucide:arrow-right")),
								h.Span(ui.Show("$sending"), g.Text(i18n.T(lang, "contact.sending"))),
							),
						),
					),
				),
			),
		),
	)
}
